#!/bin/bash

# -------
# How to use this:
#   1) Open your GCP cloud shell: https://shell.cloud.google.com/?hl=en_US&fromcloudshell=true&show=terminal
#   2) Verify that your active GCP project in uppper left corner is correct
#   3) Verify that your identity in upper right corner is correct)
#   4) Paste the following to your cloud shell
#
#          bash -c 'source <(curl -s https://raw.githubusercontent.com/isimluk/falcon-container-terraform/main/run)'
#
#

# Workaround https://github.com/hashicorp/terraform-provider-google/issues/6782
    sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1 net.ipv6.conf.default.disable_ipv6=1 net.ipv6.conf.lo.disable_ipv6=1 > /dev/null
    export APIS="googleapis.com www.googleapis.com storage.googleapis.com iam.googleapis.com container.googleapis.com cloudresourcemanager.googleapis.com"
    for name in $APIS
    do
      ipv4=$(getent ahostsv4 $name | head -n 1 | awk '{ print $1 }')
      grep -q $name /etc/hosts || ([ ! -z "ppv4" ] && sudo sh -c "echo '$ipv4 $name' >> /etc/hosts")
    done
# Workaround end


set -e -o pipefail

[ -d ~/falcon-container-terraform ] || (cd "$HOME" && git clone --depth 1 https://github.com/isimluk/falcon-container-terraform)
cd ~/falcon-container-terraform
terraform init

export TF_VAR_project_id=$(gcloud config get-value project 2> /dev/null)


terraform apply

cat <<__END__

               _ _
              (_) |             Your kubernetes cluster,
__      ____ _ _| |_            Your admin vm,
\ \ /\ / / _\` | | __|           Your Falcon Container Sensor,
 \ V  V / (_| | | |_            and Your vulnerable application,
  \_/\_/ \__,_|_|\__|           are all comming up.


__END__
sleep 60
$(terraform output admin_access | tr -d '"')

echo "Run To destroy the demo environment please run"
echo "cd ~/falcon-container-terraform; terraform destroy"
